### ISSUE TITLE
Check the classification of "pain", "privacy", and "noise" by the model

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/pxtextmining#13]
"Pain", "privacy", and "noise" may be used differently in an acute hospital than in the service the codes were designed in. Check the classification of comments containing those words- both the ratings made by humans and the model performance with them

**Comment by ChrisBeeley** [comment]
Here is a summary of the human coded responses to this https://rpubs.com/Chris_Beeley/766536

**Comment by andreassot10** [comment]
I don't understand this sentence: "Check the classification of comments containing those words- both the ratings made by humans and the model performance with them".

Do you mean, make a three-column table with the comment, coded label and predicted label?

**Comment by ChrisBeeley** [comment]
Yes. I already did human coded though, it's in the link above

**Comment by andreassot10** [comment]
You can do something like this:

```
con_text_mining <- DBI::dbConnect(
  odbc::odbc(),
  Driver   = "MySQL ODBC 8.0 Unicode Driver",
  Server   = Sys.getenv("HOST_NAME"),
  UID      = Sys.getenv("DB_USER"),
  PWD      = Sys.getenv("MYSQL_PASSWORD"),
  Port     = 3306,
  database = "TEXT_MINING",
  encoding = "UTF-8")

pain_privacy_noise <- DBI::dbGetQuery(
  con_text_mining,
  'SELECT * FROM predictions_text_data_label') %>% 
  dplyr::left_join(text_data) %>% 
  dplyr::filter(
    grepl("pain|privacy|noise", feedback, ignore.case = TRUE)
  ) %>% 
  dplyr::select(organization, feedback, label, label_pred)

View(pain_privacy_noise)
```

Table `TEXT_MINING.predictions_text_data_label` has the predicted labels for all feedback from 2/10/2020. The predictions are calculated with `factory_make_predictions.py`, a script that is currently under development (requires elaboration) and is not online yet.

Do you also want the subcategories in the table?

**Comment by ChrisBeeley** [comment]
Yes please

**Comment by andreassot10** [comment]
I'll upload a new `TEXT_MINING.text_data` on MySQL that has a `subcategory` column. (I'm actually trying to upload now, but `dbWriteTable` is unusually slow for some reason. Will try again tomorrow.)

Slight modification to the earlier script to include subcategory:

con_text_mining <- DBI::dbConnect(
  odbc::odbc(),
  Driver   = "MySQL ODBC 8.0 Unicode Driver",
  Server   = Sys.getenv("HOST_NAME"),
  UID      = Sys.getenv("DB_USER"),
  PWD      = Sys.getenv("MYSQL_PASSWORD"),
  Port     = 3306,
  database = "TEXT_MINING",
  encoding = "UTF-8")

pain_privacy_noise <- DBI::dbGetQuery(
  con_text_mining,
  'SELECT * FROM predictions_text_data_label') %>% 
  dplyr::left_join(text_data) %>% 
  dplyr::filter(
    grepl("pain|privacy|noise", feedback, ignore.case = TRUE)
  ) %>% 
  dplyr::select(organization, feedback, label, label_pred, subcategory)

View(pain_privacy_noise)
