### ISSUE TITLE
Output comment complexity

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/pxtextmining#14]
Because the tagger produces a single tag it's possible that complex comments may fail to be described well as a single tag. It may be useful for the model to tag comments that are complex. There are a number of features that could be used:

- Number of characters/ words/ sentences
- Euclidean distance between sentences vector within a document (e.g  https://radimrehurek.com/gensim/auto_examples/tutorials/run_doc2vec_lee.html)

**Comment by andreassot10** [comment]
Can you remind me what is it that you have in mind re the Euclidean distances? So we'd get a vector for each feedback text with `Doc2Vec` and then calculate the Euclidean instance of it from all other paragraph vectors? And then what? Average distance or something else?

**Comment by andreassot10** [comment]
Also, what is your definition of "document"? Is it each feedback text?

**Comment by andreassot10** [comment]
Duplicate of #10.

**Comment by andreassot10** [comment]
Duplicate of #10.
