### ISSUE TITLE
Bring back "Couldn't be improved"

### ISSUE THREAD

**Issue by andreassot10** [CDU-data-science-team/pxtextmining#15]
Split XE & XN from "Miscellaneous" label and tag them as "Couldn't be improved" (like in the old labels).

**Comment by ChrisBeeley** [comment]
Just to be clear, XN in "Best" means "Nothing was good"- that is, it was rubbish. XN in "Improve" is couldn't be improved

**Comment by andreassot10** [comment]
Thanks, I hadn't realized that. Having the same code for the different questions makes it a little tricky. Answer "Nothing" could imply that nothing was bad or that nothing was good.

So I'd have to break Misc. into either:

1. "Couldn't be improved" and Misc. (rest of minor categories, incl. "Nothing was good").
2. "Couldn't be improved", "Nothing was good" and Misc. (rest of minor categories).

The ratio of "Best" and "Improve" in terms of number of records is 11% for XN. So it seems like option 1 may make more sense for modelling purposes. Then, "Couldn't be improved" would have text for "Improve" only, and the rest of the XNs (for "Best") would be in Misc.

**Comment by milanwiedemann** [comment]
thanks, good to know! @ChrisBeeley can this be integrated in the tidy functions of the patient experience data in the nottshc pacakge?

**Comment by ChrisBeeley** [comment]
We could just recode "XN" in best into a whole new code if that's easier- "XB" or something. Of the options that @andreassot10 lists, I think 1) is better

**Comment by andreassot10** [comment]
I've now modified `notts_data_from_2020_10_01.sql` (confidential, thus not in the repo) to make "Couldn't be improved" a separate category.
