### ISSUE TITLE
Read unlabelled data from Shiny dashboard

### ISSUE THREAD

**Issue by andreassot10** [CDU-data-science-team/pxtextmining#19]
@ChrisBeeley envisions the process as follows:

1. The users will upload the unlabelled data through a button on his dashboard.
2. `reticulate` will convert the data into a `pd.DataFrame`.
3. A Python function will pull the data and saved fitted pipeline (SAV file at the time of writing), and make the predictions.

@Chris, where will the predicted data be pushed to?

**Comment by ChrisBeeley** [comment]
I need to build a dummy pipeline ASAP. I can't get it done before our meeting tomorrow (even my Shiny code isn't that fast :wink:) but basically each trust will have a separate table in the TEXT_MINING database (as they do now, we'll replace the fake data with real data when we go live)

**Comment by andreassot10** [comment]
https://github.com/CDU-data-science-team/pxtextmining/blob/development/pxtextmining/factories/factory_predict_unlabelled_text.py
