### ISSUE TITLE
Add question type as feature

### ISSUE THREAD

**Issue by andreassot10** [CDU-data-science-team/pxtextmining#23]
Adding question type as a feature would hopefully help the model associate the text with the context, that is, the question being asked.

Question context can be very wide, from "Tell us what we did best", to "Tell us what we could improve" to something completely trust-specific as "Please review our ward staff".

We will probably need to design three categories, namely, Best, Improve and the hopeless Misc that will have everything else.

Design to be carried out with @ChrisBeeley.

**Comment by yiwen-h** [comment]
My current thinking is that it might be best to have 3 different models trained on the three main types of question: 'what did we do well', 'what can we improve', and 'any general comments' (maybe using all the data for the first two models as well, we accept this model will perform more poorly). If just a feature I reckon it might get lost. For further discussion tho
