### ISSUE TITLE
Pipeline should return NULL if fed NULL

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/pxtextmining#29]
Because users of the pipeline may feed it NULL values (as part of a larger, possibly multicomment, dataframe), it would be useful to have the pipeline return NULL instead of "Miscellaneous" when it is fed a NULL value.

These kinds of things can be dealt with in upload/ reporting but it is cleaned to have some rules baked into the pipeline too (maybe adding other rules too, such as "Nothing to improve" returning "Couldn't be improved"

**Comment by yiwen-h** [comment]
Need access to SQL database to see what NULL values in SQL look like when they are in the pandas dataframe. there's a new clean_data function in factory_data_load_and_split which should drop the row if  it == str('NULL'), or pandas NaN.

**Comment by yiwen-h** [comment]
I've just realised this is more about making new predictions than about training the model? Currently factory_predict_unlabelled_text does not do much data cleaning - will add this in.

**Comment by yiwen-h** [comment]
Solved with pull request #41
