### ISSUE TITLE
Models not running

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/pxtextmining#30]
Haven't done detailed testing but one of "BernoulliNB", "ComplementNB" models in the execution.py script causes an error

**Comment by andreassot10** [comment]
I've never ever had issues with these two models. Are you sure that you are running the latest version of the package? Can I have a screenshot of the error?

**Comment by ChrisBeeley** [comment]
Haha, sorry, I sort of forgot that you would get an email about it. This was just an aide memoire to me or the new person.

I can't post the error now because the pipeline is busy but I'll post it tomorrow. If you could take a quick look I would appreciate it but don't worry about it if not. It's not really important until we kick off year 2.

**Comment by andreassot10** [comment]
Yes, I can take a look. Just post the error when you can, because I'm really curious what's causing it! I can help whenever I can, no problem at all.

**Comment by ChrisBeeley** [comment]
It's intermittent, turns out. Just got this from the criticality pipeline run, but it didn't replicate on the category pipeline this morning

![error](https://user-images.githubusercontent.com/1259867/133413342-da21de37-6952-4313-b5a1-dd85ad4463b2.png)
