### ISSUE TITLE
row_index values should be read from database

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/pxtextmining#31]
At the moment row_index in text_data *must* be fixed pre-upload as 0 : nrow(df) - 1. This is because the Python code just uses the default number of rows starting from 0 as row indices

This is non-optimal since an autoincremented PK in the database could be used as row_index and this would be robust to adding and removing rows from the database.

Change the data pipeline so that row_index is read from the data rather than generated on the fly by pandas

**Comment by yiwen-h** [comment]
at the moment text_data table does not have an autoincrementing primary key column?

**Comment by ChrisBeeley** [comment]
I just realised I said something on Slack and not on here. No, it doesn't, the row index is done by pandas which is not optimal. Better to introduce an autoincremented PK. Sloppy database design which we didn't get round to correcting in the first year
