### ISSUE TITLE
Add baseline metrics to pipeline

### ISSUE THREAD

**Issue by yiwen-h** [CDU-data-science-team/pxtextmining#45]
To help with interpretability of performance metrics, include 'baseline' of dummy model to factory_evaluate_performance

**Comment by yiwen-h** [comment]
Also it would be good to have a one page model summary in the generated folder, maybe a txt file, with all params included and performance metrics. currently all the info is in different files

**Comment by ChrisBeeley** [comment]
Yes please! :pray:
