### ISSUE TITLE
Models in results_ folders are using old pipeline

### ISSUE THREAD

**Issue by yiwen-h** [CDU-data-science-team/pxtextmining#47]
Need to replace models in results_ folders as they are using old pipeline so data cleaned with new preprocessing functions can't be used with them (shapes don't fit)

**Comment by yiwen-h** [comment]
In old model, if not enough samples (or all the same length) pipeline would break in .predict because not enough bins

**Comment by yiwen-h** [comment]
performance is not quite as good as older models - for example for 'label' prediction it's down to 0.52 class balance accuracy (from 0.53 with old pipeline) whilst with criticality prediction it's 0.38 vs 0.42 (old pipeline). maybe the additional text preprocessing has made it worse?

anyway the models should now work for predicting with api as the shapes should all fit.

**Comment by ChrisBeeley** [comment]
From memory Andreas did experiment with preprocessing I believe, I guess he just didn't document it. Probably worth trying again (?) with the new data/ codes in any case

**Comment by andreassoteriadesmoj** [comment]
> From memory Andreas did experiment with preprocessing I believe, I guess he just didn't document it.

True indeed. I regret not documenting it, especially given that I'm obsessed with documenting everything.

Faint recollection is I did some additional preprocessing at some point to hopefully improve performance, but it had the opposite effect. Quite a mystery how a text that makes more sense to humans is actually bad for the model!

**Comment by ChrisBeeley** [comment]
Also from memory, I believe @danjscho is sceptical as to the helpfulness of preprocessing (sometimes helpful, sometimes not)

**Comment by yiwen-h** [comment]
Closing this for now, will revisit preprocessing and model performance in future as a different issue.
