### ISSUE TITLE
Amend import data to account for multilabeled csv file

### ISSUE THREAD

**Issue by yiwen-h** [CDU-data-science-team/pxtextmining#58]
Phase 2 data has multiple columns with one-hot encoded labels for the text. write load_data function that will plug this new data format into existing pipeline

**Comment by yiwen-h** [comment]
Just musings:

I think in order to do this we will also need to make the number of options fewer, currently there are an almost comical number of arguments taken by the text_classification_pipeline. For example:
- objects_to_save: could probably just save all objects (leave user to delete what they don't want) 
- save_pipeline_as: just give it a default name
- metric: just leave it as class_balance_accuracy by default. 

I also feel like there should be two separate pipelines: one for the criticality / ordinal / sentiment and one for the categorical labels. Because having both in one massive pipeline makes it more unwieldy. Will make separate issue for this later.

**Comment by ChrisBeeley** [comment]
Hard agree on all counts

**Comment by yiwen-h** [comment]
load_multilabel_data function has been written. it:
- takes onehotencoded CSV, turns to pandas df
- can either take target = 'label' or target = 'sentiment' as these are the two main targets in phase 2
Basic data cleaning:
- drops NAs from features columns
- drops rows which have 0 labels
- turns qs into 3 main question types
Basic feature engineering:
- adds cols with counts of how many labels and text_length

more cleaning/etc will depend on the route forward with multilabel classification pipeline
